obj-$(CONFIG_ARCH_TSARV4_MONO_SOCLIB) += tsarv4_mono_soclib.dtb.o

obj-$(CONFIG_ARCH_TSARV5_MONO_SOCLIB) += tsarv5_mono_soclib.dtb.o
obj-$(CONFIG_ARCH_TSARV5_MULTI_SOCLIB) += tsarv5_multi_soclib.dtb.o

obj-$(CONFIG_ARCH_TSARV5_MONO_FPGA) += tsarv5_mono_fpga.dtb.o
obj-$(CONFIG_ARCH_TSARV5_MULTI_FPGA) += tsarv5_multi_fpga.dtb.o
