obj-$(CONFIG_SOCLIB_VCI_ICU) += vci_icu.o
obj-$(CONFIG_SOCLIB_VCI_XICU) += vci_xicu.o vci_xicu_timer.o
obj-$(CONFIG_SOCLIB_VCI_XICU_IOPIC) += vci_xicu_iopic.o
obj-$(CONFIG_SOCLIB_VCI_TIMER) += vci_timer.o
obj-$(CONFIG_SOCLIB_VCI_IOC) += vci_ioc.o
obj-$(CONFIG_SOCLIB_VCI_MTTY) += vci_mtty.o

