# export the following default list
include include/uapi/asm-generic/Kbuild.asm

# add those generic headers
generic-y += auxvec.h
generic-y += swab.h

# export this one as well
header-y += ucontext.h

# customized headers
header-y += byteorder.h
header-y += ptrace.h
header-y += sigcontext.h
header-y += unistd.h

