# export the following default list
include include/uapi/asm-generic/Kbuild.asm

# export this one as well
header-y += ucontext.h

# customized headers
header-y += byteorder.h
header-y += ptrace.h
header-y += sigcontext.h
header-y += unistd.h

# generic headers
generic-y += setup.h
